version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/whisper.dockerfile
    image: laravel-whisper
    container_name: laravel_whisper
    ports:
      - "8000:8000"
    volumes:
      - ./app:/var/www
    working_dir: /var/www
    environment:
      - APP_ENV=local
    command: bash -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"
